spring:
  rabbitmq:
    host: 192.168.124.14
    port: 5672
    username: fengj
    password: fengj
    virtual-host: fengJ
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1